# https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service

name: Deploy to Amazon EC2

on:
  push:
    branches: [dev, feat/backend-dev-ops]
    paths-ignore: 
      - frontend/**

jobs:
  # first stage
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - name: Check out code
        uses: actions/checkout@v2

      # setup AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_BACKEND_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_BACKEND_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # upload image to ECR
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dev-backend
          IMAGE_TAG: dev-backend
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG backend/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG