name: Run JShint Backend

on:
  push:
    branches:
      - "**"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout the repo
        uses: actions/checkout@v2

      # install
      - name: Install JShint
        run: npm install -g jshint

      # run
      - name: Run JShint
        run: jshint --exclude ./backend/node_modules backend
