name: Run Prettier Backend

on:
  push:
    branches:
      - "**"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout the repo
        uses: actions/checkout@v2

      # install
      - name: Install Prettier
        run: npm install prettier

      # run
      - name: Run Prettier
        run: npx prettier --check ./backend
